### ISSUE TITLE
Error on launch

### ISSUE THREAD

**Issue by alexrussell** [GeekyAnts/react-native-boilerplate-redux-flow#1]
Just cloned this repo today and did a `yarn` to install. Other than some peer dependency issues (see below), everything went fine.

```
warning "react-native-maps@0.15.3" has incorrect peer dependency "prop-types@^15.5.10".
warning "react-native-svg@5.3.0" has incorrect peer dependency "prop-types@^15.5.8".
warning "native-base@2.3.2" has incorrect peer dependency "react-native-vector-icons@~4.3.0".
warning "ajv-keywords@1.5.1" has incorrect peer dependency "ajv@>=4.10.0".
warning "superagent-retry@0.6.0" has incorrect peer dependency "superagent@*".
warning "superagent-proxy@1.0.2" has incorrect peer dependency "superagent@>= 0.15.4 || 1 || 2 || 3".
warning "ts-jest@21.0.1" has incorrect peer dependency "jest@^21.0.0 || ^21.1.0-alpha.1 || ^22.0.0-alpha.1".
```

However, running `yarn run ios` I get a RedBox error about ScrollView and prop types as soon as the app launches in Expo. Also a warning about `checkPropTypes` in the console.

RedBox:

![rn redbox](https://user-images.githubusercontent.com/412784/31334112-9e7e923a-ace4-11e7-85a6-b7f512c0691d.png)

Console warning:

> Warning: checkPropTypes has been moved to a separate package. Accessing React.checkPropTypes is no longer supported and will be removed completely in React 16. Use the prop-types package on npm instead. (https://fb.me/migrating-from-react-proptypes)

Running `yarn test` I get all passes but these prop type warnings are popping up. One example:

```
 PASS  src/stories/screens/BlankPage/__tests__/index.test.js (6.592s)
  ● Console

    console.error node_modules/react-native/Libraries/Core/ExceptionsManager.js:73
      Warning: PropTypes has been moved to a separate package. Accessing React.PropTypes is no longer supported and will be removed completely in React 16. Use the prop-types package on npm instead. (https://fb.me/migrating-from-react-proptypes)
    console.error node_modules/react-native/Libraries/Core/ExceptionsManager.js:73
      Warning: checkPropTypes has been moved to a separate package. Accessing React.checkPropTypes is no longer supported and will be removed completely in React 16. Use the prop-types package on npm instead. (https://fb.me/migrating-from-react-proptypes)
    console.error node_modules/react-native/Libraries/Core/ExceptionsManager.js:73
      Warning: React.createClass is no longer supported. Use a plain JavaScript class instead. If you're not yet ready to migrate, create-react-class is available on npm as a drop-in replacement. (https://fb.me/migrating-from-react-create-class)
```

Am I not supposed to be using the master branch, or is this just not ready for real world use?

I'm going to see if upgrading RN or some other packages helps, but I thought I'd let you know that if this is meant to be used for new projects, the current state of the repo is broken (at least for me).

**Comment by alexrussell** [comment]
Upgrading `react-native` to the latest release (`0.49.3`) had some effect for me. (I had to run `yarn upgrade react-native --latest`, as a standard `yarn upgrade react-native` didn't work because it would only update the "patch" version, and `0.47.2` is already the latest in the `0.47` track.)

I now get a different RedBox, and no console issues regarding prop types. However, on running `yarn test` I still get the same warnings as before.

New RedBox:

![rn redbox 2](https://user-images.githubusercontent.com/412784/31335065-d2c4fd8c-ace8-11e7-926e-51d4bd2305a6.png)

**Comment by shivrajkumar** [comment]
@alexrussell The above is version inconsistency issue. Pull the latest changes to fix the version issue

**Comment by superdopey** [comment]
I did a git clone today and the nativeVersion.major issue remains. Any tips on how to fix this?

**Comment by alexrussell** [comment]
I am no longer using this boilerplate, so this issue is no longer relevant to me. Of course, with @superdopey's interest and continuing issues it's still generally relevant, but just stating my bowing out of this process.

**Comment by shivrajkumar** [comment]
@superdopey Check [this](https://github.com/facebook/react-native/issues/16938
)
